### ISSUE TITLE
Upgrading from v0.0.3

### ISSUE THREAD

**Issue by mn-martin** [justb3a/processwire-imageextra#19]
I'm currently running a large site with thousands of images and ImageExtra v0.0.3.
As of now ImageExtra is currently the only dealbreaker for our PW > 3.* Upgrade attempt.

Is there anything to consider when upgrading?
Any experiences?
Can I just replace the module directory and hit reload?

Maybe that's something that should go into the documentation.

Thank's in advance for your answers.

**Comment by justb3a** [comment]
There is no special update routine, therefore I didn't add anything to the documentation. Just replace the module directory and reload the page. I updated several projects without any problems.  Version 1.0.0 just adds namespace support as well as some improvements (e.g. usage of textformatters) and some minor bug fixes.
