### ISSUE TITLE
Can't save orientation value

### ISSUE THREAD

**Issue by lesaff** [justb3a/processwire-imageextra#21]
Hi, this is a great module. Very useful!

I am running PW 2.8.33. I can't save `orientation` value to the db. I see the column but it's not storing anything.

**Comment by justb3a** [comment]
hi,
I never tested this module using PW 2.8 (therefore it's just official supporting PW 3.x). If the latest version 1.0.0 (using namespaces) does not work, you could try to use the [last version](https://github.com/justb3a/processwire-imageextra/archive/file-rejection.zip) supporting PW 2.7.

**Comment by lesaff** [comment]
I updated my site to 3.0.35 and it's not saving any value to the `orientation` column either.

**Comment by justb3a** [comment]
hei, I just published a new version 1.0.1. I couldn't reproduce the issue but found a litte bug: the dropdown list doesn't appear. This has been fixed now and maybe it was related to your problem?!

**Comment by lesaff** [comment]
That did it! Thanks
