### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by Toutouwai** [justb3a/processwire-imageextra#22]
I get an undefined index notice when editing an image field ~~where no additional ImageExtra fields have been set~~. (My field is called 'image' for the notice below).

> PHP Notice: Undefined index: image in ...\site\modules\ImageExtra\ImageExtra.module:832

I didn't do much investigation but changing line 832 to...

`if (isset($this->additionalFields['other'][$event->object->name]) && count($this->additionalFields['other'][$event->object->name])) {`

...seemed to solve it.

PW v3.0.35, PHP7

**Comment by Toutouwai** [comment]
Update: not a separate issue, but a side-effect of #20

**Comment by Toutouwai** [comment]
Whoops, I take that back. Issue persists, and is detectable in Tracy whenever an image field is saved in Setup > Fields.

**Comment by justb3a** [comment]
Could not reproduce this issue, nevertheless I added this additional check because it does not cause any harm 👍
