### ISSUE TITLE
JSON syntax error prevents image uploads

### ISSUE THREAD

**Issue by Toutouwai** [justb3a/processwire-imageextra#24]
I get the following errors in the JS console when attempting to upload to any image field where ImageExtra fields have been defined (either built-in fields such as caption or 'additional' fields). The effect is that image uploads are not completed and I get an endless spinner on the thumbnail.

> Firefox: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

> Chrome: Uncaught SyntaxError: Unexpected token F in JSON at position 0

Affected functions are parseJSON() in jqueryCore.js and uploadFile() in InputfieldImage.js

If I remove all defined ImageExtra fields from the image field I can upload again normally.

PW 3.0.35, PHP7

**Comment by justb3a** [comment]
fixed, thanks for reporting.
