### ISSUE TITLE
Changes case of SQL field's table name

### ISSUE THREAD

**Issue by bravokiloecho** [justb3a/processwire-imageextra#26]
After creating an image field with the name `homeMusicImage`, a table was created in the DB called: `field_homemusicimage`.

However, when I checked the "Add orientation field" in the Image Extra tab, the table was renamed to: `field_homeMusicImage` (not the camel case).

This didn't seem to cause any problems until I moved the DB to the live servers. Then when I tried to view the template that contained this field I got the following error message:

```
FieldtypeImage: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tr_dev.field_homemusicimage' doesn't exist
```

So it seems to be looking for an all-lower-case table (like all the other fields).

Can you recommend a fix for this? Many thanks!

I'm usingProcessWire 3.0.36
and PHP 7 (locally and on live server)

**Comment by bravokiloecho** [comment]
I should have said...
I'm usingProcessWire 3.0.36

**Comment by justb3a** [comment]
I guess your live server is case-sensitive. I added a hotfix which transforms the fieldname to lowercase before updating the database.

**Comment by bravokiloecho** [comment]
That's really brilliant, thanks @justb3a !

Thanks so much also for all your other work on this, it's a super helpful module and one that I imagine I will use on all my PW builds.
