### ISSUE TITLE
Issues uploading other file types

### ISSUE THREAD

**Issue by Pauldro** [justb3a/processwire-imageextra#27]
I'm trying to upload a normal file that uses the fieldtype file, the filetype I'm trying to upload is a pdf of about 470kb and it throws an error relating to Image Extra. I am using **ProcessWire 2.8.35.**

This is one of those upload issues that is the throws the JSON error : **?id=1084:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0(…)**

I was able to get a little more information out of the JavaScript Console:

<br />
<b>Notice</b>:  Undefined index: files in <b>/var/www/nwg/site/shop/site/assets/cache/FileCompiler/site/modules/ImageExtra/ImageExtra.module</b> on line <b>659</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/nwg/site/shop/site/assets/cache/FileCompiler/site/modules/ImageExtra/ImageExtra.module</b> on line <b>659</b><br />
[{"error":false,"message":"Added file: android_bluetooth_connection.pdf","file":"\/shop\/site\/assets\/files\/1084\/android_bluetooth_connection.pdf","size":457253,"markup":"\n\t<li id='file_0c3694930e848223c59004a7a4a946a8' class='InputfieldFileItem ui-widget ui-widget-content'>\n\t\t<p class='InputfieldFileInfo InputfieldItemHeader ui-state-default ui-widget-header'>\n\t\t\t<i class='fa fa-file-pdf-o fa-fw HideIfEmpty'><\/i>\n\t\t\t<a class='InputfieldFileName' title='android_bluetooth_connection.pdf' target='_blank' href='\/shop\/site\/assets\/files\/1084\/android_bluetooth_connection.pdf'>android_bluetooth_co&hellip;pdf<\/a> \n\t\t\t<span class='InputfieldFileStats'>447&nbsp;kB<\/span> \n\t\t\t<label class='InputfieldFileDelete'><input type='checkbox' name='delete_files_0c3694930e848223c59004a7a4a946a8' value='1' title='Delete' \/><i class='fa fa-fw fa-trash'><\/i><\/label>\n\t\t<\/p>\n\t\t<div class='InputfieldFileData description ui-widget-content'>\n\t\t\t<div class='InputfieldFileDescription'><label for='description_files_0c3694930e848223c59004a7a4a946a8' class='detail'>Description<\/label><input type='text' name='description_files_0c3694930e848223c59004a7a4a946a8' id='description_files_0c3694930e848223c59004a7a4a946a8' value='' \/><\/div>\n\t\t\t<input class='InputfieldFileSort' type='text' name='sort_files_0c3694930e848223c59004a7a4a946a8' value='1' \/>\n\t\t<\/div>\n\t<\/li>","replace":false,"overwrite":0}]

![capture](https://cloud.githubusercontent.com/assets/5648224/20310516/e36765a0-ab11-11e6-86cd-668bbb9a4b4e.PNG)

![pdf](https://cloud.githubusercontent.com/assets/5648224/20310368/586aa782-ab11-11e6-9330-71c2b8381ffb.png)
![2](https://cloud.githubusercontent.com/assets/5648224/20310369/586bb1f4-ab11-11e6-9443-adfedf831afa.png)

**Comment by Pauldro** [comment]
Looking at another issue #16, someone found a workaround that I was able to take an put into
the ImageExtra.Module file

In the ImageExtra.Module In the function `function processInputAddFileExtra(HookEvent $event)`
After the line 
`if ($maxFiles > 1 && $total >= $maxFiles) return;`

I entered the lines 
`$p = $event->object->value['page'];
    //added this line - without this, the pdf won't upload to the file field. $p is being returned as false
    if(!$p) return;`
which were able to let me upload pdfs without issue.

**Comment by justb3a** [comment]
hi which version of the module do you use? I've never installed PW 2.8, it's not official supported, I've no idea whether the namespace version works in PW 2.8. In fact, the module ignores all FileTypes except FileTypeImage. Using PW 3.x I can upload any other FileType without problems.

**Comment by justb3a** [comment]
Any news on this?

**Comment by Pauldro** [comment]
Sorry about that, I ended  up getting the old version of ImageExtra that ended up working with the 2.8 version, I think I'm going to just eventually can that version and move to 3.0 anyway.
