### ISSUE TITLE
Problems with TextFormatter and special chars

### ISSUE THREAD

**Issue by robo-wg** [justb3a/processwire-imageextra#28]
Hello, I use the modul first time. Great job but unfortunately no TextFormatter works for me on custom fields.
Furthermore I have problems with special characters such as __ö, ü, ä__ and so on (german language)
When these characters occur in a word and I save the page __\&auml;__ or __\&ouml;__ is displayed instead of __ä__ or __ö__ in the field. If I save the page again, the __\&auml;__ becoms __\&amp;auml;__ ...

I think the problem is on line 1242

`
$this->wire('sanitizer')->entities($pagefile->{$current});
`

Why do you use the entities-sanitizer here?

Info: Processwire 3.0.39

Kind regards, Robert

**Comment by justb3a** [comment]
Hi,

you're right, I used a wrong sanitizer there. Just pushed a hotfix into master branch.
Thanks for reporting!
