### ISSUE TITLE
InputfieldPageListSelect.min.js is loading in frontend

### ISSUE THREAD

**Issue by gebeer** [justb3a/processwire-imageextra#29]
Hello and thank you for this module!
In case we use $config->scripts to output script tags in the frontend like
```php
<?php foreach($config->scripts as $file) echo "<script type='text/javascript' src='$file'></script>\n"; ?>
```
then /wire/modules/Inputfield/InputfieldPageListSelect/InputfieldPageListSelect.min.js gets loaded.
To avoid this and have the script load only in the backend, I added `&& $backend` to the if statement in https://github.com/justb3a/processwire-imageextra/blob/master/ImageExtra.module#L112
So it reads
```php
if (isset($this->additionalFields['link']) && $backend)
```
Maybe you want to consider adding this to the next release. Thank you.

**Comment by justb3a** [comment]
Thanks! Added it to the develop branch, the next release will include it.
