### ISSUE TITLE
Notice: Undefined index: title in /.../site/modules/ImageExtra/ImageExtra.module on line 523

### ISSUE THREAD

**Issue by Rayden** [justb3a/processwire-imageextra#32]
https://github.com/justb3a/processwire-imageextra/blob/389407974e8d9a481fe0470762d7ea618bbaafcc/ImageExtra.module#L523

Please change this link to:
if (isset($page->data['title'])) {

**Comment by robo-wg** [comment]
Same problem with Repeater Matrix when there is no title-field defined

**Comment by tiefenb** [comment]
Got also this problem. I fixed it with this change:

```php
if ($page->title) {
```

**Comment by weberhofer** [comment]
#30 addresses @Rayden's issue

**Comment by justb3a** [comment]
should be fixed, see #30
