### ISSUE TITLE
Extra fields appear in preview of imageextra field in a PageTable

### ISSUE THREAD

**Issue by adrianbj** [justb3a/processwire-imageextra#7]
https://processwire.com/talk/topic/9056-module-image-extra/?p=106867

It looks like the trash icon appearing at the right of the entry in the PageTable might also be a problem with ImageExtra: https://github.com/ryancramerdesign/ProcessWire/issues/1520

**Comment by justonestep** [comment]
Same here, need to access a protected property. Wrapping the content inside `renderItem` in such a condition would fix the issue.

modules/Inputfield/InputfieldFile/InputfieldFile.module
70:     protected $renderValueMode = false;

The trash icon works fine for me:
![screen shot 2016-02-23 at 00 25 02](https://cloud.githubusercontent.com/assets/4669205/13236333/f2f5dd0a-d9c3-11e5-91c4-28be5cf3ea88.png)
